# Specify VOCs here to restrict which variants mmmvi will search for. 
# It is equivalent to the --only-vocs option.
#
# Pass this file to snakemake with --configfile option

vocs:
  - "P.1"
  - "B.1.1.7"
